name: Add PR comment

on:
  pull_request:
    types: [opened]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add PR comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PR_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;
            const prNumber = context.payload.pull_request.number;
            const deploymentUrl = `https://${prNumber}.yaoss-collection.com/`;
            const body = `Thanks for opening this PR! \n\nA deployment is available at ${deploymentUrl}.`;
            const octokit = new Octokit();
            await octokit.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body,
            });
